%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RSEQREP: RNA-Seq Reports, an open-source cloud-enabled framework for reproducible
% RNA-Seq data processing, analysis, and result reporting
% 
% https://github.com/emmesgit/RSEQREP
%
% Copyright (C) 2017 The Emmes Corporation 
% 
% This program is free software that contains third party software subject to various licenses, 
% namely, the GNU General Public License version 3 (or later), the GNU Affero General Public License 
% version 3 (or later), and the LaTeX Project Public License v.1.3(c). A list of the software contained 
% in this program, including the applicable licenses, can be accessed here: 
% 
% https://github.com/emmesgit/RSEQREP/blob/master/SOFTWARE.xlsx  
% 
% You can redistribute and/or modify this program, including its components, only under the terms of 
% the applicable license(s).  
%
% This program is distributed in the hope that it will be useful, but "as is," WITHOUT ANY WARRANTY; 
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
%
% To cite this software, please reference doi:10.12688/f1000research.13049.1
%
% Program:  rseq-02-sdeg-identification-figures.Rnw
% Version:  RSEQREP 2.2.1
% Author:   Travis L. Jensen and Johannes B. Goll
% Purpose: 	Knitr Code to build significant gene figures
% Input:    source/r/02-sdeg-identification/volcano-plots.r
%			source/r/02-sdeg-identification/ma-plots.r
%			source/r/02-sdeg-identification/upset-time-up-down.r
%			source/r/02-sdeg-identification/venn-diagram-time-up-down.r
%			source/r/02-sdeg-identification/upset-spc-up-down.r
%			source/r/02-sdeg-identification/venn-diagram-spc-up-down.r
%			source/r/02-sdeg-identification/upset-trt-up-down.r
%			source/r/02-sdeg-identification/venn-diagram-trt-up-down.r
%			source/r/02-sdeg-identification/subject-level-heatmaps.r
% Output:  	N/A
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%--------------------------------------------------------------------
%
% VOLCANO PLOTS
%
%---------------------------------------------------------------------
<<volcano_plots,fig.width=6,fig.height=12,dev='CairoPNG',dpi=300,out.width="0.6\\textwidth",fig.cap=paste('Volcano plots (',trtLabls,', ',spcLabls,').  In red:  DE genes; in grey:  genes that did not pass the fold change cut offs; in black: genes that passed the fold change cut off but were not DE.',sep='')>>= 
source(paste(src.dir,'/r/02-sdeg-identification/volcano-plots.r',sep=''));
@

%--------------------------------------------------------------------
%
% MA PLOTS
%
%---------------------------------------------------------------------
<<edger_ma_plots,fig.width=7.5,fig.height=10,dev='CairoPNG',dpi=300,out.width="0.92\\textwidth",fig.cap=paste('MA plot ',postb.times.knitr.ma.lab,'(',rep(spcLabls,each=length(postb.times.knitr.ma.lab)),'). Average \\logtwo counts per million is displayed on the x-axis, the y-axis shows average \\logtwo fold change from pre-treatment. Blue lines indicate the pre-specified minimum fold change cut off. DE genes are colored in red. Top optimize the visualization, the largest and smallest 0.1\\% of logFC observations are not included (0.1\\% < x < 99.9\\%).',sep='')>>=
source(paste(src.dir,'/r/02-sdeg-identification/ma-plots.r',sep=''));
@

%--------------------------------------------------------------------
%
% SDEG VENN DIAGRAMS AND UPSET PLOTS
%
%---------------------------------------------------------------------
<<upset_plots_time,fig.width=18,fig.height=7,out.height="0.305\\textheight",fig.cap=paste('UpSet plots summarizing overlap in DE genes between post-treatment time points (',upsetLablsTimeSdeg,'). In red: up-regulated compared to pre-treatment, in blue: down-regulated compared to pre-treatment.',sep='')>>=
source(paste(src.dir,'/r/02-sdeg-identification/upset-time-up-down.r',sep=''));
@
<<venn_diagram_plots_time,fig.width=10,fig.height=20,out.width="0.58\\textwidth",fig.cap=paste('Venn diagrams summarizing overlap in DE genes between post-treatment time points ',rep(trt.knitr.venn.glm.lab,length(spcLabls)),'(',rep(spcLabls,each=length(trt.knitr.venn.glm.lab)),'). In red: up-regulated compared to pre-treatment, in blue: down-regulated compared to pre-treatment.',sep='')>>=
source(paste(src.dir,'/r/02-sdeg-identification/venn-diagram-time-up-down.r',sep=''));
@
<<upset_plots_spc,fig.width=18,fig.height=7,out.height="0.305\\textheight",fig.cap=paste('UpSet plots summarizing overlap in DE genes between specimen types (',upsetLablsSpcSdeg,'). In red: up-regulated from pre-treatment, in blue: down-regulated from pre-treatment.',sep='')>>=
source(paste(src.dir,'/r/02-sdeg-identification/upset-spc-up-down.r',sep=''));
@
<<venn_diagram_plots_spc,fig.width=10,fig.height=20,out.width="0.58\\textwidth",fig.cap=paste('Venn diagrams summarizing overlap in DE genes between specimen types ',rep(postb.times.knitr.venn.glm.lab,length(trtFlags)),'(',rep(trtLabls,each=length(postb.times.knitr.venn.glm.lab)),'). In red: up-regulated from pre-treatment, in blue: down-regulated from pre-treatment.',sep='')>>=
source(paste(src.dir,'/r/02-sdeg-identification/venn-diagram-spc-up-down.r',sep=''));
@
<<upset_plots_trt,fig.width=18,fig.height=7,out.height="0.305\\textheight",fig.cap=paste('UpSet plots summarizing overlap in DE genes between treatment groups (',upsetLablsTrtSdeg,'). In red: up-regulated from pre-treatment, in blue: down-regulated from pre-treatment.',sep='')>>=
source(paste(src.dir,'/r/02-sdeg-identification/upset-trt-up-down.r',sep=''));
@
<<venn_diagram_plots_trt,fig.width=10,fig.height=20,out.width="0.58\\textwidth",fig.cap=paste('Venn diagrams summarizing overlap in DE genes between treatment groups ',rep(postb.times.knitr.venn.glm.lab,length(spcFlags)),'(',rep(spcLabls,each=length(postb.times.knitr.venn.glm.lab)),'). In red: up-regulated from pre-treatment, in blue: down-regulated from pre-treatment.',sep='')>>=
source(paste(src.dir,'/r/02-sdeg-identification/venn-diagram-trt-up-down.r',sep=''));
@


%--------------------------------------------------------------------
%
% SUBJECT LEVEL HEATMAPS
%
%---------------------------------------------------------------------
<<sl_heatmaps,fig.cap=paste('Heatmap of \\logtwo fold change from pre-treatment (',HeatmapLablSdeg,'). Rows represent DE genes across treatment types, columns represent samples. In red: up regulated compared to pre-treatment; in green: down-regulated compared to pre-treatment. Dendrograms were obtained using complete linkage clustering of uncentered pairwise Pearson correlation distances for \\logtwo fold changes. Samples are color-coded by treatment group (see row below sample dendrogram).',sep='')>>= 
source(paste(src.dir,'/r/02-sdeg-identification/subject-level-heatmaps.r',sep=''));
@