%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RSEQREP: RNA-Seq Reports, an open-source cloud-enabled framework for reproducible
% RNA-Seq data processing, analysis, and result reporting
% 
% https://github.com/emmesgit/RSEQREP
%
% Copyright (C) 2017 The Emmes Corporation 
% 
% This program is free software that contains third party software subject to various licenses, 
% namely, the GNU General Public License version 3 (or later), the GNU Affero General Public License 
% version 3 (or later), and the LaTeX Project Public License v.1.3(c). A list of the software contained 
% in this program, including the applicable licenses, can be accessed here: 
% 
% https://github.com/emmesgit/RSEQREP/blob/master/SOFTWARE.xlsx  
% 
% You can redistribute and/or modify this program, including its components, only under the terms of 
% the applicable license(s).  
%
% This program is distributed in the hope that it will be useful, but "as is," WITHOUT ANY WARRANTY; 
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
%
% To cite this software, please reference doi:10.12688/f1000research.13049.1
%
% Program:  rseq-04-gsea-organization-known-modules-figures.Rnw
% Version:  RSEQREP 2.1.1
% Author:   Travis L. Jensen and Johannes B. Goll
% Purpose: 	Knitr Code to build GSEA figures
% Input:    source/r/04-sdeg-organization-known-modules/gsea-upset-time.r
%			source/r/04-sdeg-organization-known-modules/gsea-venn-diagrams-time.r
%			sourcer/r/04-sdeg-organization-known-modules/gsea-upset-spc.r
%			source/r/04-sdeg-organization-known-modules/gsea-venn-diagrams-spc.r
%			source/r/04-sdeg-organization-known-modules/gsea-upset-trt.r
%			source/r/04-sdeg-organization-known-modules/gsea-venn-diagrams-trt.r
%			source/r/04-sdeg-organization-known-modules/gsea-heatmap.r
%			source/r/04-sdeg-organization-known-modules/gsea-radar-plots.r
% Output:  	N/A
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%--------------------------------------------------------------------
%
% GSEA VENN DIAGRAMS / UPSET PLOTS
%
%---------------------------------------------------------------------
<<upset_plots_gsea_time,crop=FALSE,fig.width=18,fig.height=18,out.width="1.0\\textwidth",fig.cap=paste('UpSet plots of enriched gene sets between post-treatment time points ',upsetLablsTimeGsea,sep='')>>=
source(paste(src.dir,'/r/04-sdeg-organization-known-modules/gsea-upset-time.r',sep=''));
@
<<venn_diagram_plots_gsea_time,fig.width=10,fig.height=20,out.width="0.58\\textwidth",fig.cap=paste('Venn diagrams of enriched ',rep(geneset.types,each=length(trt.knitr.venn.gsea.lab)),' between post-treatment time points ',rep(trt.knitr.venn.gsea.lab,(length(geneset.types)*length(spcLabls))),'(',rep(spcLabls,each=(length(geneset.types)*length(trt.knitr.venn.gsea.lab))),').',sep='')>>=
source(paste(src.dir,'/r/04-sdeg-organization-known-modules/gsea-venn-diagrams-time.r',sep=''));
@
<<upset_plots_gsea_spc,crop=FALSE,fig.width=18,fig.height=18,out.width="1.0\\textwidth",fig.cap=paste('UpSet plots of enriched gene sets between specimen types ',upsetLablsSpcGsea,sep='')>>= 
source(paste(src.dir,'/r/04-sdeg-organization-known-modules/gsea-upset-spc.r',sep=''));
@
<<venn_diagram_plots_gsea_spc,fig.width=10,fig.height=20,out.width="0.58\\textwidth",fig.cap=paste('Venn diagrams of enriched ',rep(geneset.types,each=length(postb.times.knitr.venn.gsea.lab)),' between specimen types ',rep(postb.times.knitr.venn.gsea.lab,(length(geneset.types)*length(trtFlags))),'(',rep(trtLabls,each=(length(geneset.types)*length(postb.times.knitr.venn.gsea.lab))),').',sep='')>>=
source(paste(src.dir,'/r/04-sdeg-organization-known-modules/gsea-venn-diagrams-spc.r',sep=''));
@
<<upset_plots_gsea_trt,crop=FALSE,fig.width=18,fig.height=18,out.width="1.0\\textwidth",fig.cap=paste('UpSet plots of enriched gene sets between treatment groups ',upsetLablsTrtGsea,sep='')>>=
source(paste(src.dir,'/r/04-sdeg-organization-known-modules/gsea-upset-trt.r',sep=''));
@
<<venn_diagram_plots_gsea_trt,fig.width=10,fig.height=20,out.width="0.58\\textwidth",fig.cap=paste('Venn diagrams of enriched ',rep(geneset.types,each=length(postb.times.knitr.venn.gsea.lab)),' between treatment groups ',rep(postb.times.knitr.venn.gsea.lab,(length(geneset.types)*length(spcLabls))),'(',rep(spcLabls,each=(length(geneset.types)*length(postb.times.knitr.venn.gsea.lab))),').',sep='')>>=
source(paste(src.dir,'/r/04-sdeg-organization-known-modules/gsea-venn-diagrams-trt.r',sep=''));
@

%--------------------------------------------------------------------
%
% GSEA HEATMAP PLOT
%
%---------------------------------------------------------------------
<<gene_set_heatmap_plots,fig.height=8,fig.cap=paste('Heatmap of enriched ',HeatmapLablGsea,' (RNA-Seq). Gene sets significantly enriched in at least two conditions are shown. Cells are color-coded by the enrichment score (-1 x $log_{10}$(FDR-adjusted p-value))). Cells contain the number of significant genes in the gene set with gene numbers in brackets indicating significantly enriched sets. Sets were clustered based on the euclidean distance between their enrichment score pattern. If there were more than 50 gene sets in the results, gene sets were further filtered to only include sets whose sum of enrichment score across conditions was the top 50 of all sets. Cells colored in grey have an enrichment score equal to zero.',sep='')>>=
source(paste(src.dir,'/r/04-sdeg-organization-known-modules/gsea-heatmap.r',sep=''));
@

%--------------------------------------------------------------------
%
% GSEA RADAR PLOT
%
%---------------------------------------------------------------------
<<gene_set_radar_plots,out.width="0.95\\textwidth",fig.height=7,fig.width=14,fig.cap=paste('Radar Plot of enriched ',RadarLablGsea,'. Gene sets significantly enriched in at least two conditions are shown.  If there were more than 26 gene sets in the results, gene sets were further filtered to only include sets whose enrichment score was the top 26 of all sets.',sep='')>>=
source(paste(src.dir,'/r/04-sdeg-organization-known-modules/gsea-radar-plots.r',sep=''));
@