%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RSEQREP: RNA-Seq Reports, an open-source cloud-enabled framework for reproducible
% RNA-Seq data processing, analysis, and result reporting
% 
% https://github.com/emmesgit/RSEQREP
%
% Copyright (C) 2017 The Emmes Corporation 
% 
% This program is free software that contains third party software subject to various licenses, 
% namely, the GNU General Public License version 3 (or later), the GNU Affero General Public License 
% version 3 (or later), and the LaTeX Project Public License v.1.3(c). A list of the software contained 
% in this program, including the applicable licenses, can be accessed here: 
% 
% https://github.com/emmesgit/RSEQREP/blob/master/SOFTWARE.xlsx  
% 
% You can redistribute and/or modify this program, including its components, only under the terms of 
% the applicable license(s).  
%
% This program is distributed in the hope that it will be useful, but "as is," WITHOUT ANY WARRANTY; 
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
%
% To cite this software, please reference doi:10.12688/f1000research.13049.1
%
% Program:  rseq-00-qc-normalization-figures.Rnw
% Version:  RSEQREP 2.0.1
% Author:   Travis L. Jensen and Johannes B. Goll
% Purpose: 	Knitr Code to build QC/normalization figures
% Input:    source/r/00-qc-normalization/qc-boxplots.r
%			source/r/00-qc-normalization/qc-bam-star-plots.r
%			source/r/00-qc-normalization/tmm-box-plots.r
%			source/r/00-qc-normalization/tmm-box-plots.r
%			source/r/00-qc-normalization/tmm-cdf-plots.r
%			source/r/00-qc-normalization/reverse-ecdf-plot.r
% Output:  	N/A
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Import analysis variables
<<variables,echo = FALSE, results= 'hide', message = FALSE>>=
source('../r/init-analysis.r')
@
%--------------------------------------------------------------------
%
% QC BOXPLOTS
%
%---------------------------------------------------------------------
<<qc_boxplots,fig.height=7.5,fig.cap=paste('Boxplots of human reference genome alignment ',bpLabel,' statistics (All specimen types).',sep='')>>=
source(paste(src.dir,'/r/00-qc-normalization/qc-boxplots.r',sep=''));
@

%--------------------------------------------------------------------
%
% BAM QC - STARPLOTS
%
%---------------------------------------------------------------------
<<star_plots,fig.cap=paste('Starplots of human reference genome alignment statistics (',spcLabls,').',sep='')>>=
source(paste(src.dir,'/r/00-qc-normalization/qc-bam-star-plots.r',sep=''));
@

%--------------------------------------------------------------------
%
% TMM NORMALIZATION QC
%
%---------------------------------------------------------------------
<<tmm_box_plots,fig.cap=paste('Boxplots of \\logtwo counts per million ',rep(c('before','after'),each=length(times.knitr.nrm.lab)),' TMM normalization ',rep(times.knitr.nrm.lab,2),'(All specimen types).',sep='')>>=
source(paste(src.dir,'/r/00-qc-normalization/tmm-box-plots.r',sep=''));
@

<<tmm_cdf_plots,fig.width=6,fig.height=7.4,out.width="1.0\\textwidth",fig.cap=paste('Empirical cumulative distribution function plots of \\logtwo counts per million before and after TMM normalization ',times.knitr.nrm.lab,'(All specimen types).',sep='')>>=
source(paste(src.dir,'/r/00-qc-normalization/tmm-cdf-plots.r',sep=''));
@

%--------------------------------------------------------------------
%
% Reverse ECDF Plot by gene espression cutoff values
%
%---------------------------------------------------------------------
<<recdf_plot,fig.width=9,fig.height=6,out.width="1.0\\textwidth",fig.cap=paste('Reverse empirical cumulative distribution function plots of ',gene_filter_method,' gene expression levels across study samples (All specimen types). The x-axis represents the \\logtwo count per million cut off for identifying lowly expressed genes. The y-axis shows the percentage of all genes whose ',gene_filter_method,' gene expression level across all study samples exceeds the respective cut off.  The grey box indicates the target range of genes to be selected (between ',flt.gene.range[1],' and ',flt.gene.range[2],' genes). The black vertical lines represent the specified cut off (',flt.lcpm.cut,' \\logtwo counts per million).',sep='')>>=
source(paste(src.dir,'/r/00-qc-normalization/reverse-ecdf-plot.r',sep=''));
@
