%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RSEQREP: RNA-Seq Reports, an open-source cloud-enabled framework for reproducible
% RNA-Seq data processing, analysis, and result reporting
% 
% https://github.com/emmesgit/RSEQREP
%
% Copyright (C) 2017 The Emmes Corporation 
% 
% This program is free software that contains third party software subject to various licenses, 
% namely, the GNU General Public License version 3 (or later), the GNU Affero General Public License 
% version 3 (or later), and the LaTeX Project Public License v.1.3(c). A list of the software contained 
% in this program, including the applicable licenses, can be accessed here: 
% 
% https://github.com/emmesgit/RSEQREP/SOFTWARE.xlsx  
% 
% You can redistribute and/or modify this program, including its components, only under the terms of 
% the applicable license(s).  
%
% This program is distributed in the hope that it will be useful, but "as is," WITHOUT ANY WARRANTY; 
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
%
% Program:  rseq-00-qc-normalization-tables.Rnw
% Version:  RSEQREP 1.0.0
% Author:   Travis L. Jensen and Johannes B. Goll
% Purpose: 	Knitr Code to build QC/normalization tables
% Input:    source/r/00-qc-normalization/tbl-excluded-genes.r
%			source/r/00-qc-normalization/qc-table.r
% Output:  	N/A
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%--------------------------------------------------------------------
%
% GENES EXCLUDED FROM ANALYIS TABLE
%
%---------------------------------------------------------------------
\FloatBarrier
<<tbl_excluded_genes,results="asis">>=
source(paste(src.dir,'/r/00-qc-normalization/tbl-excluded-genes.r',sep=''));
@

%--------------------------------------------------------------------
%
% BAM QC METRICS TABLES
%
%---------------------------------------------------------------------
\FloatBarrier
<<qc_table,results="asis">>=
source(paste(src.dir,'/r/00-qc-normalization/qc-table.r',sep=''));
@
