%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RSEQREP: RNA-Seq Reports, an open-source cloud-enabled framework for reproducible
% RNA-Seq data processing, analysis, and result reporting
% 
% https://github.com/emmesgit/RSEQREP
%
% Copyright (C) 2017 The Emmes Corporation 
% 
% This program is free software that contains third party software subject to various licenses, 
% namely, the GNU General Public License version 3 (or later), the GNU Affero General Public License 
% version 3 (or later), and the LaTeX Project Public License v.1.3(c). A list of the software contained 
% in this program, including the applicable licenses, can be accessed here: 
% 
% https://github.com/emmesgit/RSEQREP/SOFTWARE.xlsx  
% 
% You can redistribute and/or modify this program, including its components, only under the terms of 
% the applicable license(s).  
%
% This program is distributed in the hope that it will be useful, but "as is," WITHOUT ANY WARRANTY; 
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
%
% To cite this software, please reference doi:10.12688/f1000research.13049.1
%
% Program:  rseq-01-bias-confounding-effects-figures.Rnw
% Version:  RSEQREP 1.1.2
% Author:   Travis L. Jensen and Johannes B. Goll
% Purpose: 	Knitr Code to build global patterns figures
% Input:    source/r/01-bias-confounding-effects/pca-mds-plots.r
%			source/r/01-bias-confounding-effects/hcl-plots.r
% Output:  	N/A
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%--------------------------------------------------------------------
%
% SPECIMEN TYPE HIGHLIGHTS (PCA AND MULTIDIMENSIONAL SCALING)
%
%---------------------------------------------------------------------
<<pca_mds_plots,fig.width=5,fig.height=9,out.height="0.9\\textheight",fig.cap=paste('PCA and non-metric multidimensional scaling biplots (',spcLablsBias,'). PCA biplots with bivariate 95\\% confidence ellipses for standardized variables are shown at the top. Non-metric MDS results for standardized variables and pairwise differences based on Euclidean distance are shown in the middle.  Non-metric MDS results for original variables based on 1-Spearman correlation distance are shown at the bottom. Labels for the four most outlying samples per laboratory based on maximum Mahalanobis distance are shown. Strong outliers are highlighted in blue.',sep='')>>=
source(paste(src.dir,'/r/01-bias-confounding-effects/pca-mds-plots.r',sep=''));
@

%--------------------------------------------------------------------
%
% HIERARCHICAL CLUSTERING
%
%---------------------------------------------------------------------
<<all_hcl_plots,fig.width=8,fig.height=11,out.height="0.9\\textheight",out.width="0.8\\textwidth",fig.cap=paste('Hierarchical clustering plots (',spcLabls,'). Euclidean distances hierarchically clustered using the complete linkage clustering algorithm. Outliers are marked by a blue circle next to the sample ID.',sep='')>>=
source(paste(src.dir,'/r/01-bias-confounding-effects/hcl-plots.r',sep=''));
@

