%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RSEQREP: RNA-Seq Reports, an open-source cloud-enabled framework for reproducible
% RNA-Seq data processing, analysis, and result reporting
% 
% https://github.com/emmesgit/RSEQREP
%
% Copyright (C) 2017 The Emmes Corporation 
% 
% This program is free software that contains third party software subject to various licenses, 
% namely, the GNU General Public License version 3 (or later), the GNU Affero General Public License 
% version 3 (or later), and the LaTeX Project Public License v.1.3(c). A list of the software contained 
% in this program, including the applicable licenses, can be accessed here: 
% 
% https://github.com/emmesgit/RSEQREP/blob/master/SOFTWARE.xlsx  
% 
% You can redistribute and/or modify this program, including its components, only under the terms of 
% the applicable license(s).  
%
% This program is distributed in the hope that it will be useful, but "as is," WITHOUT ANY WARRANTY; 
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
%
% To cite this software, please reference doi:10.12688/f1000research.13049.1
%
% Program:  rseq-03-sdeg-clusters-figures.Rnw
% Version:  RSEQREP 2.1.1
% Author:   Travis L. Jensen and Johannes B. Goll
% Purpose: 	Knitr Code to build significant gene cluster figures
% Input:    source/r/03-sdeg-clusters/pvclusters-hcl-plots.r
%			source//r/03-sdeg-clusters/pvclusters-time-trend.r
% Output:  	N/A
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%--------------------------------------------------------------------
%
% SDEG CLUSTER BOOTSTRAP PLOTS
%
%---------------------------------------------------------------------
<<pvclust_hcl_plot,out.width="1.0\\textwidth",fig.cap=paste('Co-expressed gene cluster dendrogram with bootstrap probabilities (',DendrLabls,'). The y axis shows the distance at which clusters were formed by the complete linkage clustering algorithm based on uncentered Pearson correlation distance between \\logtwo fold changes. Multiscale bootstrap probabilities are shown at each branch intersection. Significant clusters are highlighted in blue. Asterisks indicate genes that were significantly expressed at a certain day.',sep='')>>=
source(paste(src.dir,'/r/03-sdeg-clusters/pvclusters-hcl-plots.r',sep=''));
@

%--------------------------------------------------------------------
%
% SDEG CLUSTER TREND PLOTS
%
%---------------------------------------------------------------------
<<pvclust_trend_plot,fig.width=6,fig.height=8,out.width="0.95\\textwidth",fig.cap=paste('Co-expressed gene cluster time trends of \\logtwo fold change from pre-treatment levels by treatment ',TrendLabls,'. Header indicates cluster ID. Mean \\logtwo fold change across cluster genes is drawn in bold. Individual mean gene \\logtwo fold changes are plotted in lighter colors.',sep='')>>=
source(paste(src.dir,'/r/03-sdeg-clusters/pvclusters-time-trend.r',sep=''));
@
